version: '3'

services:
  aethalometer-processor:
    build: .
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./app/data:/app/app/data
      - ./app/static:/app/app/static
    environment:
      - PORT=${PORT:-5000}
    restart: unless-stopped
