version: '3'

services:
  aethalometer-processor:
    build: .
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    volumes:
      - ./app/data:/app/app/data
      - ./app/static:/app/app/static
    environment:
      - PORT=${PORT:-8080}
    restart: unless-stopped
