services:
  aethalometer-processor:
    build: .
    ports:
      - "${PORT:-3000}:5000"
    volumes:
      - ./app/data:/app/app/data
      - ./app/static:/app/app/static
    environment:
      - PORT=5000
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8081}:80"
    depends_on:
      - aethalometer-processor
    restart: unless-stopped
